-- MySQL Script generated by MySQL Workbench
-- Sat Apr 30 02:29:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema safekey
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `safekey` ;

-- -----------------------------------------------------
-- Schema safekey
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `safekey` DEFAULT CHARACTER SET utf8 ;
USE `safekey` ;

-- -----------------------------------------------------
-- Table `contatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contatos` (
  `idContato` INT NOT NULL AUTO_INCREMENT,
  `paisContato` VARCHAR(45) NOT NULL,
  `estadoContato` VARCHAR(45) NOT NULL,
  `cidadeContato` VARCHAR(45) NOT NULL,
  `bairroContato` VARCHAR(45) NULL,
  `ruaContato` VARCHAR(45) NOT NULL,
  `numRes` INT NOT NULL,
  `numAptBloco` INT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `cod_pais_1` VARCHAR(5) NOT NULL,
  `ddd_1` VARCHAR(5) NOT NULL,
  `tel_1` VARCHAR(20) NOT NULL,
  `cod_pais_2` VARCHAR(5) NULL,
  `ddd_2` VARCHAR(5) NULL,
  `tel_2` VARCHAR(20) NULL,
  `email_1` VARCHAR(255) NOT NULL,
  `email_2` VARCHAR(255) NULL,
  `dtnasc` DATE NOT NULL,
  PRIMARY KEY (`idContato`),
  UNIQUE INDEX `tel_1_UNIQUE` (`tel_1` ASC) VISIBLE,
  UNIQUE INDEX `tel_2_UNIQUE` (`tel_2` ASC) VISIBLE,
  UNIQUE INDEX `email_2_UNIQUE` (`email_2` ASC) VISIBLE,
  UNIQUE INDEX `email_1_UNIQUE` (`email_1` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clientes` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nmCliente` INT NOT NULL,
  `cpfCliente` DECIMAL(11,0) NOT NULL,
  `idContatoCliente` INT NOT NULL,
  `dtcadastro` DATE NOT NULL,
  PRIMARY KEY (`cpfCliente`),
  KEY `idCliente`(`idCliente`),
  UNIQUE INDEX `cpfCliente_UNIQUE` (`cpfCliente` ASC) VISIBLE,
  UNIQUE INDEX `nmCliente_UNIQUE` (`nmCliente` ASC) VISIBLE,
  INDEX `idContatoCliente_idx` (`idContatoCliente` ASC) VISIBLE,
  CONSTRAINT `idContatoCliente`
    FOREIGN KEY (`idContatoCliente`)
    REFERENCES `contatos` (`idContato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veiculos` (
  `idVeiculos` INT NOT NULL AUTO_INCREMENT,
  `placa` CHAR(7) NOT NULL,
  `idCliente` DECIMAL(11,0) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `ano` DATE NOT NULL,
  `cor` VARCHAR(45) NULL,
  `obs` TEXT(225) NULL,
  PRIMARY KEY (`placa`),
  KEY `idVeiculos`(`idVeiculos`),
  UNIQUE INDEX `idveiculos_UNIQUE` (`idVeiculos` ASC) VISIBLE,
  UNIQUE INDEX `Placa_UNIQUE` (`placa` ASC) VISIBLE,
  INDEX `idCliente_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `clientes` (`cpfCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa` (
  `idEmpresa` INT NOT NULL AUTO_INCREMENT,
  `nmEmpresa` VARCHAR(45) NOT NULL,
  `razaoSocial` VARCHAR(255) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `capitalSocial` INT NOT NULL,
  `idContato` INT NOT NULL,
  `inscEstadual` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `idfiscal_UNIQUE` (`idEmpresa` ASC) VISIBLE,
  PRIMARY KEY (`cnpj`),
  KEY `idEmpresa`(`idEmpresa`),
  INDEX `idContatoEmpresa_idx` (`idContato` ASC) VISIBLE,
  CONSTRAINT `idContatoEmpresa`
    FOREIGN KEY (`idContato`)
    REFERENCES `contatos` (`idContato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `suporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suporte` (
  `idSuporte` INT NOT NULL AUTO_INCREMENT,
  `mtFun` INT NOT NULL,
  `nmFunc` VARCHAR(100) NOT NULL,
  `setorFunc` VARCHAR(45) NOT NULL,
  `nivelFunc` VARCHAR(45) NOT NULL,
  `cargoFun` VARCHAR(45) NOT NULL,
  `idContatoFunc` INT NOT NULL,
  `dtcontratado` DATE NOT NULL,
  `idEmpresa` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`mtFun`),
  KEY `idSuporte`(`idSuporte`),
  UNIQUE INDEX `idsuporte_UNIQUE` (`idSuporte` ASC) VISIBLE,
  INDEX `idContatoFun_idx` (`idContatoFunc` ASC) VISIBLE,
  UNIQUE INDEX `mtFun_UNIQUE` (`mtFun` ASC) VISIBLE,
  INDEX `idEmpresa_idx` (`idEmpresa` ASC) VISIBLE,
  CONSTRAINT `idContatoFun`
    FOREIGN KEY (`idContatoFunc`)
    REFERENCES `contatos` (`idContato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idEmpresa`
    FOREIGN KEY (`idEmpresa`)
    REFERENCES `empresa` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locker` (
  `idLocker` INT NOT NULL AUTO_INCREMENT,
  `numLocker` INT NOT NULL,
  `endLocker` VARCHAR(145) NOT NULL,
  `cidadeLocker` VARCHAR(45) NOT NULL,
  `obsEndLocker` TEXT(255) NULL,
  `dataInstalado` VARCHAR(45) NOT NULL,
  `statusLocker` TINYINT NOT NULL,
  `idFuncResp` INT NOT NULL,
  `idEmpresa` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`numLocker`),
  KEY `idLocker` (`idLocker`),
  UNIQUE INDEX `idlocker_UNIQUE` (`idLocker` ASC) VISIBLE,
  UNIQUE INDEX `numLocker_UNIQUE` (`numLocker` ASC) VISIBLE,
  INDEX `idFun_idx` (`idFuncResp` ASC) VISIBLE,
  INDEX `idMantenedora_idx` (`idEmpresa` ASC) VISIBLE,
  CONSTRAINT `idFunRes`
    FOREIGN KEY (`idFuncResp`)
    REFERENCES `suporte` (`mtFun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idMantenedora`
    FOREIGN KEY (`idEmpresa`)
    REFERENCES `empresa` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compartimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compartimento` (
  `idComp` INT NOT NULL AUTO_INCREMENT,
  `numComp` INT NOT NULL,
  `idLocker` INT NOT NULL,
  `statusComp` TINYINT NOT NULL,
  `dispComp` TINYINT NOT NULL,
  PRIMARY KEY (`numComp`),
  KEY `idComp` (`idComp`),
  UNIQUE INDEX `idcompartimento_UNIQUE` (`idComp` ASC) VISIBLE,
  INDEX `idLocker_idx` (`idLocker` ASC) VISIBLE,
  UNIQUE INDEX `numComp_UNIQUE` (`numComp` ASC) VISIBLE,
  CONSTRAINT `idLocker`
    FOREIGN KEY (`idLocker`)
    REFERENCES `locker` (`numLocker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tarifa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarifa` (
  `idtarifa` INT NOT NULL AUTO_INCREMENT,
  `nmtarifa` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(9,2) NOT NULL,
  `dataImplantada` DATETIME(2) NOT NULL,
  `obsTarifa` VARCHAR(45) NOT NULL,
  `idFun` INT NOT NULL,
  `timeTarifa` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`idtarifa`),
  UNIQUE INDEX `idtarifa_UNIQUE` (`idtarifa` ASC) VISIBLE,
  INDEX `idFun_idx` (`idFun` ASC) VISIBLE,
  CONSTRAINT `idFunAut`
    FOREIGN KEY (`idFun`)
    REFERENCES `suporte` (`mtFun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pagamento` (
  `idPago` INT NOT NULL AUTO_INCREMENT,
  `formaPago` VARCHAR(45) NOT NULL,
  `dataPago` TIMESTAMP NOT NULL,
  `statusPago` TINYINT NOT NULL,
  `valorPago` DECIMAL(9,2) NOT NULL,
  UNIQUE INDEX `idpagamento_UNIQUE` (`idPago` ASC) VISIBLE,
  PRIMARY KEY (`idPago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cliente_locker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente_locker` (
  `idContrato` INT NOT NULL AUTO_INCREMENT,
  `numContrato` INT NOT NULL,
  `idVeiculo` CHAR(7) NOT NULL,
  `idcompartimento` INT NOT NULL,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `obsContrato` TEXT(225) NULL,
  `idTarifa` INT NOT NULL,
  `statusContrato` TINYINT NOT NULL,
  `idPagamento` INT NOT NULL,
  PRIMARY KEY (`numContrato`),
  KEY `idContrato` (`idContrato`),
  UNIQUE INDEX `idcliente_locker_UNIQUE` (`idContrato` ASC) VISIBLE,
  INDEX `idCompartimento_idx` (`idcompartimento` ASC) VISIBLE,
  INDEX `idVeiculo_idx` (`idVeiculo` ASC) VISIBLE,
  UNIQUE INDEX `numContrato_UNIQUE` (`numContrato` ASC) VISIBLE,
  INDEX `idTarifa_idx` (`idTarifa` ASC) VISIBLE,
  INDEX `idPagamento_idx` (`idPagamento` ASC) VISIBLE,
  CONSTRAINT `idVeiculo`
    FOREIGN KEY (`idVeiculo`)
    REFERENCES `veiculos` (`placa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCompartimento`
    FOREIGN KEY (`idcompartimento`)
    REFERENCES `compartimento` (`numComp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idTarifa`
    FOREIGN KEY (`idTarifa`)
    REFERENCES `tarifa` (`idtarifa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPagamento`
    FOREIGN KEY (`idPagamento`)
    REFERENCES `pagamento` (`idPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acesso_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acesso_clientes` (
  `idacesso` INT NOT NULL AUTO_INCREMENT,
  `idcliente` DECIMAL(11,0) NOT NULL,
  `usuario` VARBINARY(520) NOT NULL,
  `senha` VARBINARY(520) NOT NULL,
  `datacriacao` DATETIME(2) NOT NULL,
  PRIMARY KEY (`idacesso`),
  UNIQUE INDEX `idpass_UNIQUE` (`idacesso` ASC) VISIBLE,
  INDEX `idUser_idx` (`idcliente` ASC) VISIBLE,
  CONSTRAINT `idUserClie`
    FOREIGN KEY (`idcliente`)
    REFERENCES `clientes` (`cpfCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acesso_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acesso_funcionario` (
  `idacesso` INT NOT NULL AUTO_INCREMENT,
  `idfun` INT NOT NULL,
  `usuario` VARBINARY(520) NOT NULL,
  `senha` VARBINARY(520) NOT NULL,
  `datacriacao` DATETIME(2) NOT NULL,
  PRIMARY KEY (`idacesso`),
  UNIQUE INDEX `idpass_UNIQUE` (`idacesso` ASC) VISIBLE,
  INDEX `idUser_idx` (`idfun` ASC) VISIBLE,
  CONSTRAINT `idUserFun`
    FOREIGN KEY (`idfun`)
    REFERENCES `suporte` (`mtFun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notafiscal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notafiscal` (
  `idNF` INT NOT NULL AUTO_INCREMENT,
  `numNF` VARBINARY(255) NOT NULL,
  `idtomador` DECIMAL(11,0) NOT NULL,
  `idfornecedor` VARCHAR(14) NOT NULL,
  `idServico` INT NOT NULL,
  UNIQUE INDEX `idnotafiscal_UNIQUE` (`idNF` ASC) VISIBLE,
  INDEX `idTomador_idx` (`idtomador` ASC) VISIBLE,
  INDEX `idFornecedor_idx` (`idfornecedor` ASC) VISIBLE,
  PRIMARY KEY (`numNF`),
  KEY `idNF`(`idNF`),
  INDEX `idServico_idx` (`idServico` ASC) VISIBLE,
  CONSTRAINT `idTomador`
    FOREIGN KEY (`idtomador`)
    REFERENCES `clientes` (`cpfCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idFornecedor`
    FOREIGN KEY (`idfornecedor`)
    REFERENCES `empresa` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idServico`
    FOREIGN KEY (`idServico`)
    REFERENCES `cliente_locker` (`numContrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

